### ISSUE TITLE
Attributes is empty

### ISSUE THREAD

**Issue by bsde1234** [jxson/front-matter#91]
When I tried to get contents of a yml file, attributes is empty, but body have contents

**Comment by jxson** [comment]
Could you provide an example set of content that yeilds the same result? I can use it to debug and maybe set up a regression test if there is a bug.

**Comment by bsde1234** [comment]
```
title: "xxxxxx xxx"
url: "https://xxxxx.com/xx"
email: "xxxx@gmail.com"
markdown: kramdown
mobile: "xxxxxxx"
country: "xxxx"
currency_code: "xx"
  style: compressed
defaults:
  - scope:
      type: posts
    values:
      layout: product
  - scope:
      type: products
    values:
      layout: post
encoding: UTF-8
favicon: "logo.png"

```




```
var fs = require('fs')
  , fm = require('front-matter')


fs.readFile('../xxxx/xx/_config.yml', 'utf8', function(err, data2){

  if (err) throw err

  var content2 = fm(data2)

  console.log(content2)

})


```
